1. Below is some indian companies revenues in US dollars. Using numpy can you convert this into Indian rupees? 1 USD = 75 INR

In [1]:
import numpy as np

In [5]:
array1 = np.array([[200, 220, 250], [68,79,105], [110, 140, 180], [80, 85, 90]])

In [6]:
array1

array([[200, 220, 250],
       [ 68,  79, 105],
       [110, 140, 180],
       [ 80,  85,  90]])

In [ ]:
# Result in INR

In [7]:
array1 * 75

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

2. Divine flowers is a flower shop that sells different type of flowers. Below is the table showing how many flowers of each type they sold in different months. Also given are the prices of one flower each. Using this find out their total sales in every month.

In [26]:
unit_sold = np.array([[50, 60, 25],[10,13,5],[40,70,52]])
price_per_unit = np.array([20,30,15])

In [24]:
unit_sold

array([[50, 60, 25],
       [10, 13,  5],
       [40, 70, 52]])

In [27]:
price_per_unit

array([20, 30, 15])

In [30]:
price_per_unit * unit_sold

array([[1000, 1800,  375],
       [ 200,  390,   75],
       [ 800, 2100,  780]])

In [29]:
np.dot(price_per_unit, unit_sold)

array([1900, 2640, 1430])