In [2]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [4]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0]) # First 4 are positive reviews, and next ones are negative review.

In [5]:
one_hot("amazing restaurant", 30)


[23, 9]

In [6]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[21, 18], [23, 9], [19, 10], [15, 1, 4], [25, 13, 15], [15, 18], [23, 13, 14], [14, 27], [14, 10], [19, 11]]


In [7]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen = max_length, padding = 'post')
padded_reviews

array([[21, 18,  0,  0],
       [23,  9,  0,  0],
       [19, 10,  0,  0],
       [15,  1,  4,  0],
       [25, 13, 15,  0],
       [15, 18,  0,  0],
       [23, 13, 14,  0],
       [14, 27,  0,  0],
       [14, 10,  0,  0],
       [19, 11,  0,  0]])

In [8]:
embedded_vector_size = 5

In [10]:
model = Sequential()
model.add(Embedding(vocab_size, embedded_vector_size, input_length = max_length, name = "embedding"))
model.add(Flatten())
model.add(Dense(1, activation = 'sigmoid'))


In [11]:
X = padded_reviews
y = sentiment

In [13]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten (Flatten)           (None, 20)                0         
                                                                 
 dense (Dense)               (None, 1)                 21        
                                                                 
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.fit(X, y, epochs = 50, verbose = 0)


In [15]:
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 1s 1s/step - loss: 0.6431 - accuracy: 1.0000


1.0

In [17]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [18]:
weights[11]

array([-0.01470051,  0.03143293,  0.09770288,  0.00123196,  0.0254473 ],
      dtype=float32)

In [19]:
weights[3]

array([ 0.00556777,  0.01379571, -0.04529728, -0.02677658, -0.010098  ],
      dtype=float32)